const modalToggle = require('./modules/modalToggle')
const newModalToggle = require('./modules/newModalToggle')
const sureModalToggle = require('./modules/sureModalToggle')
const newSelect = require('./modules/select')
const date = require('./modules/date')
const dateCloseOne = require('./modules/dateCloseOne')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')

modalToggle()
newModalToggle()
sureModalToggle()
newSelect()
date()
dateCloseOne()
title()
deleteElem()