const modalToggle = require('./modules/modalToggle')
const newModalToggle = require('./modules/newModalToggle')
const sureModalToggle = require('./modules/sureModalToggle')
const newSelect = require('./modules/select')
const date = require('./modules/date')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')
const zoom = require('./modules/zoom')

modalToggle()
newModalToggle()
sureModalToggle()
newSelect()
date()
title()
deleteElem()
zoom()