const modalToggle = require('./modules/modalToggle')
const newModalToggle = require('./modules/newModalToggle')
const sureModalToggle = require('./modules/sureModalToggle')
const date = require('./modules/date')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')
const zoom = require('./modules/zoom')
const back = require('./modules/backZoom')

modalToggle()
newModalToggle()
sureModalToggle()
date()
title()
deleteElem()
zoom()
back()