const modalToggle = require('./modules/modalToggle')
const sureModalToggle = require('./modules/sureModalToggle')
const date = require('./modules/date')
const dateCloseOne = require('./modules/dateCloseOne')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')
const selectOpen = require('./modules/selectOpen')

modalToggle()
sureModalToggle()
date()
dateCloseOne()
title()
deleteElem()
selectOpen()