const modalToggle = require('./modules/modalToggle')
const newModalToggle = require('./modules/newModalToggle')
const sureModalToggle = require('./modules/sureModalToggle')
const date = require('./modules/date')
const dateCloseOne = require('./modules/dateCloseOne')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')
const selectOpen = require('./modules/selectOpen')
const range = require('./modules/range')
const pause = require('./modules/pause')
const back = require('./modules/backZoom')

modalToggle()
newModalToggle()
sureModalToggle()
date()
dateCloseOne()
title()
deleteElem()
selectOpen()
range()
pause()
back()