const modalToggle = require('./modules/modalToggle')
const sureModalToggle = require('./modules/sureModalToggle')
const date = require('./modules/date')
const dateCloseOne = require('./modules/dateCloseOne')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')
const selectOpen = require('./modules/selectOpen')
const zoom = require('./modules/zoom')
const range = require('./modules/range')
const pause = require('./modules/pause')

modalToggle()
sureModalToggle()
date()
dateCloseOne()
title()
deleteElem()
selectOpen()
zoom()
range()
pause()