const modalToggle = require('./modules/modalToggle')
const newModalDonate = require('./modules/newModalDonate')
const sureModalToggle = require('./modules/sureModalToggle')
const date = require('./modules/date')
const title = require('./modules/title')
const deleteElem = require('./modules/delete')
const zoom = require('./modules/zoom')

modalToggle()
newModalDonate()
sureModalToggle()
date()
title()
deleteElem()
zoom()